server:
  port: 9999

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: email-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/emails/**
        - id: lesson
          uri: http://localhost:8080
          predicates:
            - Path=/api/lesson/**
        - id: chess-exercise
          uri: https://chess-2-load-balancer-891026373.eu-north-1.elb.amazonaws.com
          predicates:
            - Path=/api/chess_exercise/**


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
